## Machine Learning Lab Practical 5 (Part 1) - TensorFlow (13/09/2024)

ชื่อ นายฉัตรดนัย ปูทอง

รหัสนักศึกษา 116510462029-9

e-mail earthtyjoy11@gmail.com

# 1. พื้นฐานการพัฒนาการใช้งาน TensorFlow library

นศ. สามารถศึกษาเพิ่มเติมได้จาก [TensorFlow basics](https://www.tensorflow.org/guide/basics#tensors) และ [Introduction to Tensors](https://www.tensorflow.org/guide/tensor)

1.1 การ import TensorFlow library

In [ ]:
import tensorflow as tf

1.2 การตรวจสอบเวอร์ขันของ TensorFlow library

In [ ]:
print(tf.__version__)

2.17.0


1.3 ตัวอย่างการประเภทของมูล Tensor

In [ ]:
import tensorflow as tf

x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])

print(x)
print("----------------------------------")
print(x.shape)
print("----------------------------------")
print(x.dtype)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
----------------------------------
(2, 3)
----------------------------------
<dtype: 'float32'>


1.4 ตัวอย่าง operator การบวก ใน Tensor

In [ ]:
x + x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

1.5 ตัวอย่าง transpose

In [ ]:
tf.transpose(x)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

1.6 ตัวอย่างการทำ dot product ใน Tensor (dot product ใช้เครื่องหมาย @)

In [ ]:
x @ tf.transpose(x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

1.7 คำนวณ Softmax

In [ ]:
# axis = 0
tf.nn.softmax(x, axis=0)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.04742587, 0.04742587, 0.04742587],
       [0.95257413, 0.95257413, 0.95257413]], dtype=float32)>

In [ ]:
# axis = 1
tf.nn.softmax(x, axis=1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09003057, 0.24472848, 0.66524094],
       [0.09003057, 0.24472848, 0.66524094]], dtype=float32)>

In [ ]:
# axis = -1
tf.nn.softmax(x, axis=-1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09003057, 0.24472848, 0.66524094],
       [0.09003057, 0.24472848, 0.66524094]], dtype=float32)>

1.8 คำนวณค่า sum ในข้อมูล Tensor

In [ ]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=21.0>

In [ ]:
tf.reduce_sum(x, axis=0)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([5., 7., 9.], dtype=float32)>

In [ ]:
tf.reduce_sum(x, axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 6., 15.], dtype=float32)>

1.9 การแปลงข้อมูล array เป็น Tensor

In [ ]:
tf.convert_to_tensor([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
tf.convert_to_tensor([[1,2,3]])

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

1.10 ตัวอย่างข้อมูล Tensor ใน dimension ต่างๆ

In [ ]:
# scalar or "rank-0" tensor
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

print("---------------------------------------------")
# A "vector" or "rank-1" tensor is like a list of values. A vector has one axis:
# Let's make this a float tensor.
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

print("---------------------------------------------")
# # A "matrix" or "rank-2" tensor has two axes:
# # If you want to be specific, you can set the dtype (see below) at creation time
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

print("---------------------------------------------")
# # Rank-3 tensor
# # There can be an arbitrary number of
# # axes (sometimes called "dimensions")
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],

  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],

  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(4, shape=(), dtype=int32)
---------------------------------------------
tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
---------------------------------------------
tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)
---------------------------------------------
tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


1.11 การตรวจสอบมีการใช้งาน GPU หรือไม่



In [ ]:
import tensorflow as tf

if tf.config.list_physical_devices('GPU'):
  print("TensorFlow **IS** using the GPU")
else:
  print("TensorFlow **IS NOT** using the GPU")

TensorFlow **IS NOT** using the GPU


1.12 convert tensor to numpy

In [ ]:
import numpy as np
import tensorflow as tf


rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
np.array(rank_2_tensor)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

# 2. การสร้าง Linear Regression Model โดยใช้ TensorFlow

2.1 เรียนรู้การสร้างโมเดล Linear Regression อย่างง่าย โดยใช้ไลพรารี่ของ TensorFlow [Reference](https://developers.google.com/codelabs/tensorflow-1-helloworld#0)

In [ ]:
import tensorflow as tf
import numpy as np

x_train = np.array([-1, 0, 1, 2, 3, 4], dtype=float)
y_tain = np.array([-3, -1, 1, 3, 5, 7], dtype=float)

model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(units=1, input_shape=[1])
])

model.compile(optimizer='sgd', loss='mean_squared_error')
model.summary()

model.fit(x_train, y_tain, epochs=500, verbose=0)

x_new = np.array([10])
y_hat = model.predict(x_new)
print (f"predict x new ({x_new}) = {y_hat}")


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 1)                   │               2 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
predict x new ([10]) = [[18.98625]]


2.2 การ clear session

เมื่อรันคำสั่ง `model.fit` ในแต่ละครั้ง TensorFlow จะมีการสร้าง session ซึ่งจดจำสถานะและค่าพารามิเตอร์ต่าง ๆ ไว้ ดังนั้นหากมีการเรียก `model.fit` ซ้ำในแต่ละครั้ง ก็จะเป็นการ train ต่อเนื่องจากครั้งก่อนหน้า

ดังนั้น หากต้องการเริ่มต้นการ train model ใหม่ตั้งแต่ต้น จำเป็นต้อง clear session ก่อน โดยการเรียก method `clear_session()` ดังตัวอย่างต่อไปนี้

In [ ]:
from keras.backend import clear_session
clear_session()

2.3 ทดลองเปลี่ยนค่า epochs จาก 500 เป็น 2000 และสังเกตุผลที่ได้


In [ ]:
import tensorflow as tf
import numpy as np

x_train = np.array([-1, 0, 1, 2, 3, 4], dtype=float)
y_tain = np.array([-3, -1, 1, 3, 5, 7], dtype=float)

model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(units=1, input_shape=[1])
])

model.compile(optimizer='sgd', loss='mean_squared_error')
model.summary()

model.fit(x_train, y_tain, epochs=2000, verbose=0)

x_new = np.array([10])
y_hat = model.predict(x_new)
print (f"predict x new ({x_new}) = {y_hat}")


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 1)                   │               2 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
predict x new ([10]) = [[18.999987]]



```
# เพิ่มค่า epoch ทำให้จำนวนรอบที่โมเดลถูกฝึกด้วยข้อมูลเพิ่มขึ้น
```

☝☝☝ ให้ นศ. เขียนคำอธิบายผลที่ที่นี่  ☝☝☝




 2.4 ทดลองเปลี่ยนค่า verbose จาก 0 เป็น 1 และสังเกตุผลที่ได้


In [ ]:
import tensorflow as tf
import numpy as np

x_train = np.array([-1, 0, 1, 2, 3, 4], dtype=float)
y_tain = np.array([-3, -1, 1, 3, 5, 7], dtype=float)

model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(units=1, input_shape=[1])
])

model.compile(optimizer='sgd', loss='mean_squared_error')
model.summary()

model.fit(x_train, y_tain, epochs=500, verbose=1)

x_new = np.array([10])
y_hat = model.predict(x_new)
print (f"predict x new ({x_new}) = {y_hat}")


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                      │ (None, 1)                   │               2 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 209ms/step - loss: 1.5023
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 1.3185
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 1.1711
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 1.0523
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.9562
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.8780
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.8138
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.7609
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.7167
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.6795
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.6479
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.6207
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.5970
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.5761
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.5575
Epoch 16/500
1/1 ━


```
# การเปลี่ยนค่า verbose เป็น 1 ทำให้แสดงผลการฝึกในแต่ละรอบของโมเดล
```

☝☝☝ ให้ นศ. เขียนคำอธิบายผลที่ที่นี่  ☝☝☝


